import type { Metadata } from 'next'
import { Catamaran } from 'next/font/google'
import './globals.css'
import { RsvpBanner } from './components/RsvpBanner'
import { Navbar } from './components/Navbar'
import { Providers } from './Providers'
import { PHProvider, PostHogPageview } from './providers/posthog'
import { Suspense } from 'react'
import { Analytics } from '@vercel/analytics/react';

const bodyFont = Catamaran({ subsets: ['latin'], variable: '--font-body', display: 'swap' })

export const metadata: Metadata = {
  title: 'Clare & Ian are getting married',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${bodyFont.variable}`}>
      <Suspense>
        <PostHogPageview />
      </Suspense>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/jfe8gfh.css" />
      </head>
      <PHProvider>
        <body>
          <RsvpBanner />
          <Navbar />
          <Providers>
            {children}
            <Analytics />
          </Providers>
        </body>
      </PHProvider>
    </html>
  )
}