import type { Metadata } from 'next'
import { Catamaran } from 'next/font/google'
import './globals.css'
import { RsvpBanner } from './components/RsvpBanner'
import { Navbar } from './components/Navbar'
import { Providers } from './Providers'

const bodyFont = Catamaran({ subsets: ['latin'], variable: '--font-body', display: 'swap' })

export const metadata: Metadata = {
  title: 'Clare & Ian are getting married',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${bodyFont.variable}`}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/jfe8gfh.css" />
      </head>
      <body>
        <RsvpBanner />
        <Navbar />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}